// Setting and Retrieving Cookies
import jakarta.servlet.*;
import jakarta.servlet.http.*;
import java.io.*;

public class form_B extends HttpServlet {
   public void doPost( HttpServletRequest request,                  // reaction to the reception of POST
                       HttpServletResponse response )   throws ServletException, IOException
   {
      PrintWriter output;
      String form_A = request.getParameter("form_A");   // choice made will be sent back to client
      response.setContentType( "text/html" );
      output = response.getWriter();         
       // send HTML page to client
      output.println( "<!DOCTYPE html><html><style>"
+"@import url('https://fonts.googleapis.com/css?family=Ubuntu');"

+"body { background-image: url('images/shattered_@2X.png'); }"

+"h1 { text-shadow: 1px 1px 2px #000000; font-size: 40px; font-family: 'Ubuntu', sans-serif; padding-bottom: 10px; }"

+"h3 { font-size: 19px; font-family: 'Ubuntu', sans-serif; padding-bottom: 10px; }"

+"input[type=text] {"
+"  text-align: center;" 
+"    width: 215px;"
+"    box-sizing: border-box;"
+"    border: 2px solid #ccc;"
+"    border-radius: 4px;"
+"    font-size: 16px;"
+"    padding: 12px 15px 12px 15px;"
+"    -webkit-transition: width 0.4s ease-in-out;"
+"    transition: width 0.4s ease-in-out;"
+"}"

+"input[type=text]:focus {"
 +"   width: 20%;"
+"}"

+"input[type='checkbox'],"
+"input[type='radio'] {"
+"  position: absolute;"
+"  opacity: 0;"
+"  z-index: -1;"
+"}"
+"label {" 
+"  position: relative;"
+"  display: inline-block;"
+"  line-height: 35px;"
+"  width: 80px;"
+"  cursor: pointer;"
+"}"
+"label::before {"
+"  content: ' ';"
+"  position: absolute;"
+"  display: block;"
+"  width: 26px;"
+"  height: 26px;"
+"  z-index: -1;"
+"}"

+"input[type='radio'] + label::before {"
+"  border-radius: 12px;"
+"  left : -5px;"
+"}"
+"input[type='checkbox']:checked + label,"
+"input[type='radio']:checked + label {"
+"  color: #fff;"
+"}"

+"input[type='checkbox']:checked + label::before,"
+"input[type='radio']:checked + label::before {"
+"  padding-left: 10px;"
+"  width: 100%;"
+"  height: 100%;"
+"  background: #000000;"
+"}"
+"label,"
+"label::before {"
+"  -webkit-transition: .25s all ease;"
+"  -o-transition: .25s all ease;"
+"  transition: .25s all ease;"
+"}"

+"input[type=submit] {"
+"    background-color: #000000; /* Green */"
+"    border: none;"
+"    color: white;"
+"    width: 90px;"
+"    padding: 7px 10px;"
+"    font-family: Ubuntu;"
+"    text-align: center;"
+"    text-decoration: none;"
+"    display: inline-block;"
+"    font-size: 16px;"
+"    margin: 4px 2px;"
+"    border-radius: 12px;"
+"    -webkit-transition-duration: 0.4s; /* Safari */"
+"    transition-duration: 0.4s;"
+"    cursor: pointer;"
+"}"
+"input[type=submit] {"
+"    background-color: white;" 
+"    color: black; "
+"    border: 2px solid #000000;"
+"}"

+"input[type=submit]:hover {"
+"    background-color: #000000;"
+"    color: white;"
+"}"

+"select {"
+"  font-family: Ubuntu;"
+"}"

+"div { margin: 20px; }"

+".styled-select {"
+"   background: url(http://i62.tinypic.com/15xvbd5.png) no-repeat 96% 0;"
+"   height: 29px;"
+"   overflow: hidden;"
+"   width: 240px;"
+"}"

+".styled-select select {"
+"   background: transparent;"
+"   border: none;"
+"   font-size: 14px;"
+"   height: 29px;"
+"   padding: 5px;"
+"   width: 268px;"
+"}"

+".semi-square {"
+"   -webkit-border-radius: 5px;"
+"   -moz-border-radius: 5px;"
+"   border-radius: 5px;"
+"}"

+".black    { background-color: #000000; }"

+".black select    { color: #fff; }"

+"select#soflow, select#soflow-color {"
+"   -webkit-appearance: button;"
+"   -webkit-border-radius: 2px;"
+"   -webkit-box-shadow: 0px 1px 3px rgba(0, 0, 0, 0.1);"
+"   -webkit-padding-end: 20px;"
+"   -webkit-padding-start: 2px;"
+"   -webkit-user-select: none;"
+"   background-position: 97% center;"
+"   background-repeat: no-repeat;"
+"   border: 1px solid #AAA;"
+"   color: #555;"
+"   font-size: inherit;"
+"   margin: 20px;"
+"   overflow: hidden;"
+"   padding: 5px 10px;"
+"   text-overflow: ellipsis;"
+"   white-space: nowrap;"
+"   width: 300px;"
+"}"

+"select#soflow-color {"
+"   color: #fff;"
+"   background-color: #779126;"
+"   -webkit-border-radius: 20px;"
+"   -moz-border-radius: 20px;"
+"   border-radius: 20px;"
+"   padding-left: 15px;"
+"}"

+".rbutton {"
+"  display: inline-block;"
+"  border-radius: 8px;"
+"  background-color: #000000;"
+"  border: none;"
+"  color: #FFFFFF;"
+"  font-family: Ubuntu;"
+"    text-align: center;"
+"  font-size: 20px;"
+"  padding: 8px;"
+"  width: 110px;"
+"  transition: all 0.5s;"
+"  cursor: pointer;"
+"  margin: 5px;"
+"}"

+".rbutton span {"
+"  cursor: pointer;"
+"  display: inline-block;"
+"  position: relative;"
+"  transition: 0.5s;"
+"}"

+".rbutton span:after {"
+"  content: '<';"
+"  position: absolute;"
+"  opacity: 0;"
+"  top: 0;"
+"  left: -20px;"
+"  transition: 0.5s;"
+"}"

+".rbutton:hover span {"
+"  padding-left: 25px;"
+"}"

+".rbutton:hover span:after {"
+"  opacity: 1;"
+"  left: 0;"
+"}"
+"</style>"
+"<body>"
+"<center>" );
	  if (form_A.equals("clothing")){
		  output.println("<h1>Clothing</h1>"
+"<h3>Please choose type of clothing:</h3>"
+"<form action='form_C' method='POST'>"
+"<div class='styled-select black semi-square'>"  
+"<select name='form_B'>"
+"  <option value='a T-shirt'>T-shirts</option>"
+"  <option value='a pair of Trousers'>Trousers</option>"
+"  <option value='a pair of Shoes'>Shoes</option>"
+"  <option value='a Jacket'>Jackets</option>"
+"  <option value='a Skirt'>Skirts</option>"
+"  <option value='a Dress'>Dress</option>"
+"  <option value='a Coat'>Coats</option>"
+"  <option value='a Belt'>Belts</option>");
      }
      else if (form_A.equals("toys")){
		  output.println("<h1>Toys</h1>"
+"<h3>Please choose type of toy:</h3>"
+"<form action='form_C' method='POST'>"
+"  <div class='styled-select black semi-square'>"
+"<select name='form_B'>"
+"  <option value='an Action Figure'>Action Figure</option>"
+"  <option value='a Doll'>Doll</option>"
+"  <option value='a Puzzle'>Puzzle</option>"
+"  <option value='Building Blocks'>Building Blocks</option>"
+"  <option value='a Bike'>Bike</option>"
+"  <option value='a Table Game'>Table Game</option>");  
      } 
      else if (form_A.equals("electronics")){
		  output.println("<h1>Electronics</h1>"
+"<h3>Please choose type of electric appliance:</h3>"
+"<form action='form_C' method='POST'>"
+"  <div class='styled-select black semi-square'>"
+"<select name='form_B'>"
+"  <option value='an Air Conditioner'>Air Conditioner</option>"
+"  <option value='a Blender'>Blender</option>"
+"  <option value='a Vacuum Cleaner'>Vacuum Cleaner</option>"
+"  <option value='a Clothes Dryer'>Clothes Dryer</option>"
+"  <option value='a Dishwasher'>Dishwasher</option>"
+"  <option value='a Hair Dryer'>Hair Dryer</option>"
+"  <option value='a Microwave Oven'>Microwave Oven</option>"
+"  <option value='a Television'>Television</option>"
+"  <option value='a Toaster'>Toaster</option>");  
      } 
      else if (form_A.equals("plane")){
		  output.println("<h1>Plane</h1>"
+"<h3>Please choose a destination:</h3>"
+"<form action='form_C' method='POST'>"
+"  <div class='styled-select black semi-square'>"
+"<select name='form_B' >"
+"  <option value='a flight to Athens'>Athens</option>"
+"  <option value='a flight to Atlanta'>Atlanta</option>"
+"  <option value='a flight to Baltimore'>Baltimore</option>"
+"  <option value='a flight to Barcelona'>Barcelona</option>"
+"  <option value='a flight to Beijing'>Beijing</option>"
+"  <option value='a flight to Budapest'>Budapest</option>"
+"  <option value='a flight to Buenos Aires'>Buenos Aires</option>"
+"  <option value='a flight to Chicago'>Chicago</option>"
+"  <option value='a flight to Delhi'>Delhi</option>"
+"  <option value='a flight to Dublin'>Dublin</option>"
+"  <option value='a flight to Frankfurt'>Frankfurt</option>"
+"  <option value='a flight to Helsinki'>Helsinki</option>"
+"  <option value='a flight to Lisbon'>Lisbon</option>"
+"  <option value='a flight to London'>London</option>"
+"  <option value='a flight to Madrid'>Madrid</option>"
+"  <option value='a flight to Paris'>Paris</option>");  
      } 
      else if (form_A.equals("train")){
		  output.println("<h1>Train</h1>"
+"<h3>Please choose a train route:</h3>"
+"<form action='form_C' method='POST'>"
+"  <div class='styled-select black semi-square'>"
+"<select name='form_B'>"
+"  <option value='a train trip from Paris to Amsterdam'>Paris to Amsterdam</option>"
+"  <option value='a train trip from Paris to Barcelona'>Paris to Barcelona</option>"
+"  <option value='a train trip from Madrid to Barcelona'>Madrid to Barcelona</option>"
+"  <option value='a train trip from Paris to Geneva'>Paris to Geneva</option>"
+"  <option value='a train trip from Amsterdam to Berlin'>Amsterdam to Berlin</option>"
+"  <option value='a train trip from Berlin to Prague'>Berlin to Prague</option>"
+"  <option value='a train trip from Prague to Vienna'>Prague to Vienna</option>"
+"  <option value='a train trip from Vienna to Budapest'>Vienna to Budapest</option>");  
      } 
      else if (form_A.equals("bus")){
		  output.println("<h1>Bus</h1>"
+"<h3>Please choose a destination:</h3>"
+"<form action='form_C' method='POST'>"
+"  <div class='styled-select black semi-square'>"
+"<select name='form_B' >"
+"  <option value='a bus trip to Thessaloniki'>Thessaloniki</option>"
+"  <option value='a bus trip to Patras'>Patras</option>"
+"  <option value='a bus trip to Larisa'>Larisa</option>"
+"  <option value='a bus trip to Ioannina'>Ioannina</option>"
+"  <option value='a bus trip to Corinth'>Corinth</option>"
+"  <option value='a bus trip to Nafplio'>Nafplio</option>"
+"  <option value='a bus trip to Chalcis'>Chalcis</option>"
+"  <option value='a bus trip to Xanthi'>Xanthi</option>");  
      } 
      output.println("</select>"
+"</div>"
+"  <input type='submit' value='Submit'>"
+"</form> "
+"</center>"
+"</body>"
+"</html>");
      output.close ();    // close stream
   }
}
